[env:custom_build]
extends = env:esp32c3dev_4MB_M
build_flags = ${env:esp32c3dev_4MB_M.build_flags} -D LOLIN_WIFI_FIX -D WLED_DISABLE_MQTT -D WLED_DISABLE_LOXONE -D WLED_DISABLE_HUESYNC -D DATA_PINS= -D RLYPIN=0 -D RLYMDE=0 -D ABL_MILLIAMPS_DEFAULT=0 -D LED_TYPES= -D DEFAULT_LED_COLOR_ORDER= -D MAX_LEDS=40 -D CLIENT_SSID='"ESPEETJE"' -D CLIENT_PASS='"0594249321"'   -D USERMOD_UART_PRESET_NOTIFIER
