name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/wled/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'platform = espressif32' >>platformio.ini
        echo 'board = esp32-c3-devkitm-1' >>platformio.ini
        echo 'framework = arduino' >>platformio.ini
                echo 'build_flags =' >>platformio.ini
        echo '  ${env:esp32c3dev_4MB_M.build_flags}' >>platformio.ini
        echo '  -D WLED_DISABLE_MQTT' >>platformio.ini
        echo '  -D WLED_DISABLE_LOXONE' >>platformio.ini
        echo '  -D WLED_DISABLE_HUESYNC' >>platformio.ini
        echo '  -D WLED_DISABLE_SNTP' >>platformio.ini
        echo '  -D WLED_DISABLE_CRONIXIE' >>platformio.ini
        echo '  -D WLED_DISABLE_TIME' >>platformio.ini
        echo '  -D USERMOD_ENABLE_TEMPERATURE=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_SENSOR=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_DALLAS=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_IMU=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_HDC1080=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_NTP=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_PIR=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_SHT=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_TELEINFO=false' >>platformio.ini
        echo '  -D USERMOD_ENABLE_DHT=false' >>platformio.ini
        echo '  -D USERMOD_UART_PRESET_NOTIFIER' >>platformio.ini
        echo '  -D DATA_PINS=4' >>platformio.ini
        echo '  -D RLYPIN=16' >>platformio.ini
        echo '  -D RLYMDE=1' >>platformio.ini
        echo '  -D ABL_MILLIAMPS_DEFAULT=0' >>platformio.ini
        echo '  -D LED_TYPES=' >>platformio.ini
        echo '  -D DEFAULT_LED_COLOR_ORDER=' >>platformio.ini
        echo '  -D MAX_LEDS=40' >>platformio.ini
        echo '  -D CLIENT_SSID="\"ESPEETJE\""' >>platformio.ini
        echo '  -D CLIENT_PASS="\"0594249321\""' >>platformio.ini
        echo '' >>platformio.ini
        echo 'build_unflags= -D WLED_RELEASE_NAME' >>platformio.ini

        mkdir -p /tmp/WLEDtemp/`cat /tmp/WLEDtemp/wledfoldername`/usermods/usermod_uart_preset_notifier
        cp $GITHUB_WORKSPACE/usermods/usermod_uart_preset_notifier/usermod_uart_preset_notifier.cpp /tmp/WLEDtemp/`cat /tmp/WLEDtemp/wledfoldername`/usermods/usermod_uart_preset_notifier/

        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
