name: WLED compile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Run PlatformIO
        run: |
          rm -rf /tmp/WLEDtemp/* || true
          mkdir -p /tmp/WLEDtemp
          wget https://github.com/Robainee/wledmetap/raw/main/WLED-main.zip -O /tmp/WLEDtemp/mm.zip
          unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
          WLEDFOLDERNAME=$(find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -type d -name "WLED-main*")
          cd $WLEDFOLDERNAME

          mkdir -p ./usermods/usermod_uart_preset_notifier
          cp $GITHUB_WORKSPACE/usermods/usermod_uart_preset_notifier/usermod_uart_preset_notifier.cpp ./usermods/usermod_uart_preset_notifier/

          mkdir -p ./usermods/usermod_multi_relay
          cp $GITHUB_WORKSPACE/usermods/usermod_multi_relay/usermod_multi_relay.cpp ./usermods/usermod_multi_relay/

          cat <<EOF >> platformio.ini

          echo '[env:esp01_1m_full]' >> platformio.ini
          echo 'platform = espressif8266' >> platformio.ini
          echo 'board = esp01_1m' >> platformio.ini
          echo 'framework = arduino' >> platformio.ini
          echo 'build_flags = -D USERMOD_INCLUDE="usermod_uart_preset_notifier.cpp usermod_multirelay.cpp" -D LEDPIN=4 -D RLYPIN=16 -D RLYMDE=1 -D MAX_LEDS=40 -D LED_TYPES=TYPE_WS2812_RGB -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_GRB -D ABL_MILLIAMPS_DEFAULT=800 -D USERMOD_ENABLE_TEMPERATURE=false -D USERMOD_ENABLE_SENSOR=false -D WLED_DISABLE_MQTT -D WLED_DISABLE_LOXONE -D WLED_DISABLE_HUESYNC -D WLED_DISABLE_FLOWS -D WLED_DISABLE_INFRARED -D WLED_DISABLE_BLYNK -D WLED_DISABLE_CRONIXIE' >> platformio.ini
          echo 'build_unflags = -D BOARD_HAS_PSRAM -D WLED_USE_PSRAM -D WLED_USE_PSRAM_JSON -D ALL_JSON_TO_PSRAM -D WLED_DISABLE_OTA' >> platformio.ini
          echo 'upload_speed = 115200' >> platformio.ini
          echo 'monitor_speed = 74880' >> platformio.ini


          cp -r wled00 src
          pio run -e esp01_1m_full || pio run -e esp01_1m_full

      - name: Copy Files
        run: |
          cd $GITHUB_WORKSPACE
          find /tmp/WLEDtemp/WLED-main/WLED-main/.pio/build/esp01_1m_uart/ -name '*.bin' -exec cp {} $GITHUB_WORKSPACE/ \;

          date -I | tr -d '\n' > $GITHUB_WORKSPACE/last_update_date.txt

      - name: Commit Files
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@users.noreply.github.com"
          git add *.bin || true
          git add last_update_date.txt
          git commit -m "Commit Custom Build" || echo "Nothing to commit"
          git push origin main || echo "Nothing to push"
